spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
